apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      nodeSelector:
        node-role: worker   # 👈 This makes sure only worker nodes are used
      containers:
        - name: node-app
          image: sainathmitalakar/my-node-microservice:latest
          ports:
            - containerPort: 4000

